sudo: required

services:
  - docker

install:
  - npm install -g codecov

script:
  - docker-compose up --force-recreate coverage

after_success:
  # - docker-compose up --force-recreate coveralls
  - codecov
