sudo: required
language: node_js
services:
  - docker
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.11"
script: docker-compose up --force-recreate --abort-on-container-exit
after_success:
  - npm run coveralls
