sudo: required

services:
  - docker

# skip install
install: true

script:
  - docker-compose up --force-recreate test

after_success:
  # - docker-compose up --force-recreate coveralls
  - bash <(curl -s https://codecov.io/bash)
