sudo: required

language: node_js
node_js:
  - "6"
  - "7"
  - "8"

services:
  - docker

install:
  - npm install -g codecov
  - npm install

script:
  - docker version
  - docker run -d -p "8200:8200" vault
  - docker ps
  - npm run coverage

after_success:
  - codecov
