sudo: required

services:
  - docker

install:
  - npm install -g codecov

script:
  - docker-compose up --force-recreate test

after_success:
  # - docker-compose up --force-recreate coveralls
  - codecov
